### ISSUE TITLE
`self::PYTHON_PATH` is not documented in pyenv.md but `dependancy_info()` refers to this class constant

### ISSUE THREAD

**Issue by MrWaloo** [NebzHB/dependance.lib#11]
While activating the plugin, there is a php error revealed in the `http.error` log file :
```log
PHP Fatal error:  Uncaught Error: Undefined class constant 'PYTHON_PATH' in /var/www/html/plugins/mymodbus/core/class/mymodbus.class.php:342\nStack trace:\n#0 /var/www/html/core/class/plugin.class.php(733): mymodbus::dependancy_info()\n#1 /var/www/html/core/class/plugin.class.php(1024): plugin->dependancy_info()\n#2 /var/www/html/core/ajax/plugin.ajax.php(54): plugin->setIsEnable()\n#3 {main}\n  thrown in /var/www/html/plugins/mymodbus/core/class/mymodbus.class.php on line 342
```
The line 342 contains 
```php
   } elseif (!self::pythonRequirementsInstalled(self::PYTHON_PATH, __DIR__ . '/../../resources/requirements.txt')) {
```
... in the `dependancy_info()` function.

According to Mips WorxLandroidS plugin, it should be set like this in the eqLogic:
https://github.com/Mips2648/jeedom-worxLandroidS/blob/6bc3e8ef13ad86114c6bfb53fdf2cb4cc870dac5/core/class/worxLandroidS.class.php#L24C5-L24C71

```php
const PYTHON_PATH = __DIR__ . '/../../resources/venv/bin/python3';
```

This is not documented in `pyenv.md`

**Comment by Mips2648** [comment]
Hi,
Indeed, because it was just an example, 
actually it is not in the scope of this lib. I've adapted the documentation accordingly.
