### ISSUE TITLE
pythonRequirementsInstalled returns false if a module is installed with an option

### ISSUE THREAD

**Issue by MrWaloo** [NebzHB/dependance.lib#15]
In requirements.txt, I had:
```
jeedomdaemon >= 1.0.2
pymodbus [serial] == 3.7.3
```
It used to work until today (maybe 2 days ago, when the module has been updated). Now I have to write:
```
jeedomdaemon >= 1.0.2
pyserial == 3.5
pymodbus == 3.7.3
```

The only difference is that pymodbus V3.7.3 is not the latest version, but `pymodbus/pyproject.toml` did not change for this option.

**Comment by Mips2648** [comment]
Hi,

If i understood correctly this is not linked to the dependencies
installation itself so out of scope of this lib.

The php snipet that I provided is not  actually part of this lib (but
https://github.com/Mips2648/jeedom-tools) and the syntax above was not
supported

**Comment by MrWaloo** [comment]
Thanks for your answer.
Yes it is only to let you know, that the syntax with an option on requirements.txt is not supported. What I don't really understand is why it used to work. According to the used regex, it shouldn't. I did not know how/where to let you know...
The lib works fine.

If I make a PR to support the syntax with options, will you accept it?

**Comment by Mips2648** [comment]
There is no code to adapt except an example in the doc so I don't understand what would be the content of the PR.

**Comment by Mips2648** [comment]
btw, this should work:
```
pymodbus[serial] == 3.7.3
```
so no space between `pymodbus` and `[serial]`

**Comment by MrWaloo** [comment]
Sadly it doesn't. Even without any space.
As I understood, you won't accept any PR to fix it, so I close this issue but without solution.

Thanks anyway for your job :-)

**Comment by Mips2648** [comment]
Je vais répondre en français puisqu'apparament c'était pas clair:

1. Ne transforme pas mes propos: J'ai demandé des éclaircissements sur ce
que tu voulais car ce n'est pas clair. Je n'ai pas répondu que je
refuserais le pr (ni que je l'accepterais non plus d'ailleurs). Ca me
paraît évident qu'il est nécessaire de savoir de quoi on parle avant de
dire si on est d'accord ou pas...
Bref, je ne sais toujours pas de quel "fix" tu parles ni de quel code
d'ailleurs. Est-ce du code se trouvant dans les sources de ce repo?
2. Le contournement que j'ai proposé fonctionne, je l'ai testé (avec ce que
j'avais compris). Je ne l'aurais pas proposé sinon.

**Comment by MrWaloo** [comment]
Aucun problème de mon coté, je ne cherche pas à transformer les propos de qui que ce soit.
Mon but ici est d'arriver à une solution, peu importe si elle vient de moi ou de qui que ce soit. Je dois mal m'exprimer et/ou mal comprendre, je vais tacher de reprendre.
Ne vois rien d'offensant ni de provocateur dans ce que j'écris.

1. C'est la fonction pythonRequirementsInstalled proposée ici :

https://github.com/NebzHB/dependance.lib/blob/master/pyenv.md
et qui fait partie de ton autre bibliothèque php pour Jeedom (jeedom-tools) mais que je n'utilise pas (encore ?) parce que je ne connaissais pas son existence.
Cette fonction donc, je l'ai copiée dans mon plugin et elle retourne false de toute évidence, vu le résultat.

> There is no code to adapt

Pour moi ça signifie que tout est bon et que l'erreur est de mon coté, pourtant...

2. Mes tests : 
```
pymodbus[serial] == 3.7.4
```
Puis réinstallation des dépendances --> les logs semblent OK puisqu'identiques à quand ça fonctionne mais : 
![image](https://github.com/user-attachments/assets/3ecb7f1b-2529-4fea-8ad5-92d2cf878618)
Donc la mise à jour est effectivement faite mais la fonction pythonRequirementsInstalled retourne false

```
pymodbus[serial]==3.7.4
```
Identique (non fonctionnel)

```
pyserial == 3.5
pymodbus == 3.7.4
```
Fonctionnel, tout est au vert.

Ma machine de test est en 4.4.18, mais je pense que ça fonctionne comme sous 4.4.19.
Entre 2 essais, j'ai toujours relancé avec la syntaxe fonctionnelle pour être sûr que la syntaxe testée "cassait" le résultat.

----

Donc je pense (mais peux me tromper) que la 1ère regex pourrait prévoir le cas d'une option entre crochets (et l'ignorer) et isoler le nom du module à installer seul. Un truc de ce genre (testé et satisfaisant) :
```php
    foreach ($packages_needed as $line) {
        if (preg_match('/([^\s\[]+).*?([>=~]=)[\s]*([\d+\.?]+)$/', $line, $need) === 1) {
```
Comme la regex que tu utilises ne teste que des espaces entre le nom du module et le comparateur (si on peut l'appeler comme ça) avec la syntaxe `pymodbus[serial] == 3.7.4` ça ne matche pas. Avec ma proposition, ça le fait.
Je pense implémenter cette adaptation mais voulais t'en faire un retour. Si tu penses toujours qu'il n'y a rien à adapter, je tournerai avec ma version mais j'aurais au moins essayé de te le partager, ce qui est le but de l'open source.

**Comment by Mips2648** [comment]
Deux axes: 
1. je ne vais pas maintenir le code de la doc ici que j'avais juste mis en exemple pour (dé)montrer ce qu'il était possible, je pense plutôt le supprimer (ou en tout cas préciser que ce n'est pas maintenu/à adapter) et ajouter un lien vers https://github.com/Mips2648/jeedom-tools où le code maintenu se trouve.
2. j'ai adapté la regex pour aller même plus loin que ce que tu proposes, je pense que tous les cas (https://pip.pypa.io/en/stable/reference/requirement-specifiers/) sont prévus à présent
le commit est ici: https://github.com/Mips2648/jeedom-tools/commit/dcaaf045b2575e414bfb645c1d84440b70638235
les tests unitaires démontrent tout ce qui est supporté
j'ai mis la regex et les cas testés ici également, c'est plus visuel: https://regex101.com/r/6uTgL2/1
j'ai ajouté les "named group" pour que ca soit plus facile de se retrouver dans la lecture de la regex
---
attention, dans le code de jeedom-tools il me reste à gérer les cas où aucune version n'a été précisée, autrement la regex va fonctionner mais pas le test après, je n'ai plus le temps de faire ca ce soir

**Comment by MrWaloo** [comment]
1. OK, c'est clair au moins. Top
2. Très bien

Merci pour la prise en compte de ce cas.
J'étudierai jeedom-tools de plus près à l'occasion.

Pour taquiner, je dirais bien que finalement il y a eu une adaptation ;-)
Mais comme je ne veux pas que ce soit mal interprété, je ne le dis pas.

Juste pour la petite histoire : 
En y réfléchissant, la raison pour laquelle la fonction a fonctionné c'est parce qu'au début j'avais mis `pymodbus [serial] < 3.8` mais comme le passage de 3.7.3 à 3.7.4 de pymodbus n'était pas sans changement API (alors que ça le devrait...) j'ai changé en `pymodbus [serial] == 3.7.3` puis 3.7.4 une fois les adaptations faites. Le cas '<' n'est pas géré et la fonction retourne true, donc ça fonctionnait.

**Comment by Mips2648** [comment]
> Pour taquiner, je dirais bien que finalement il y a eu une adaptation ;-)

j'espère que ca t'a fait du bien, mais vraiment beaucoup de bien car moi ca m'a fait beaucoup de tord... c'est précisément pour ce genre de commentaire que je n'ai plus envie de répondre;

1. depuis le début, cette issue est hors sujet avec le repo puisqu'on parle d'un bout de code qui n'existe pas dans le code ici.
2. je n'ai jamais soutenu que les cas des "extra dependencies" était géré/fonctionnel et qu'il ne fallait pas adapter le code de la dite fonction; au contraire c'était indiqué que ce n'était pas géré.

**Comment by MrWaloo** [comment]
Pas du tout, je pensais juste mettre une touche d'humour. Toutes mes excuses si j'ai pu te froisser.

1. En effet, je m'en suis rendu compte quand tu as parlé de ta lib que je ne connaissais pas
2. Effectivement, j'allais utiliser une version modifiée et en rester là, tu as choisi de faire une adaptation et je pense qu'elle sera profitable à d'autres

A priori je ne suis pas doué pour m'exprimer à l'écrit, je me contenterai dorénavant du strict minimum pour ne plus en arriver là.

Encore toutes mes excuses
